using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Atelier.Generators;

/// <summary>
/// Generates <c>MaterialIcons</c> in the assembly that defines <c>Atelier.Controls.MaterialIconKind</c>: a string
/// constant with the name of every icon, for places that take icons as text, such as the <c>Icon</c> of a
/// <c>[Command]</c> attribute (attribute arguments can't be enum values of another library's type there, and strings
/// get no code completion). The constants are <c>nameof</c> expressions, so they always match the enum.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class MaterialIconNamesGenerator : IIncrementalGenerator
{
    private const string EnumMetadataName = "Atelier.Controls.MaterialIconKind";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Only the icon names are compared between runs, so edits elsewhere in the assembly don't regenerate the file.
        var names = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var kind = compilation.GetTypeByMetadataName(EnumMetadataName);
            if (kind == null || !SymbolEqualityComparer.Default.Equals(kind.ContainingAssembly, compilation.Assembly))
            {
                return EquatableArray<string>.Empty;
            }

            return new EquatableArray<string>(kind.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f.HasConstantValue && f.Name != "None")
                .Select(f => f.Name)
                .ToArray());
        });

        context.RegisterSourceOutput(names, static (spc, iconNames) =>
        {
            if (iconNames.Count == 0) return;
            spc.AddSource("MaterialIcons.g.cs", SourceText.From(Generate(iconNames), Encoding.UTF8));
        });
    }

    private static string Generate(EquatableArray<string> names)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace Atelier.Controls");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// The names of the <see cref=\"MaterialIconKind\"/> icons as string constants, for icons given as text, such as the");
        sb.AppendLine("    /// <c>Icon</c> of a <c>[Command]</c> attribute or <see cref=\"Icon.Source\"/>:");
        sb.AppendLine("    /// <c>[Command(\"Save\", \"Editor\", Icon = MaterialIcons.Save)]</c>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>Generated from <see cref=\"MaterialIconKind\"/> at compile time.</remarks>");
        sb.AppendLine("    public static class MaterialIcons");
        sb.AppendLine("    {");
        foreach (string name in names)
        {
            sb.AppendLine($"        /// <summary>The <see cref=\"MaterialIconKind.{name}\"/> icon.</summary>");
            sb.AppendLine($"        public const string {name} = nameof(MaterialIconKind.{name});");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
