<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HarfBuzzSharp" Version="14.2.1.201" />
    <PackageReference Include="SkiaSharp" Version="4.152.1" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="4.152.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atelier.Core\Atelier.Core.csproj" />
    <ProjectReference Include="..\Atelier.Layout\Atelier.Layout.csproj" />
  </ItemGroup>

</Project>
