using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using Atelier.Core.Events;
using Atelier.Core.Primitives;
using Atelier.Core.Properties;
using Atelier.Core.Tree;
using Atelier.Layout;

namespace Atelier.Controls;

/// <summary>
/// A node of a <see cref="TreeView"/>: a header row (indentation, expander, content) above its child nodes.
/// </summary>
/// <remarks>
/// Nodes are usually generated by the tree from its items, but can also be built manually with
/// <see cref="AddChildItem"/> and <see cref="TreeView.AddRootItem"/> in any order. Children from a
/// <see cref="SetChildrenSource">children source</see> are created lazily, the first time the node is expanded or
/// <see cref="ChildrenItems"/> is read. A left click on the header selects the node, a double click toggles it; right and
/// middle clicks are left to the application.
/// </remarks>
public class TreeViewItem : Control
{
    /// <summary>Identifies the <see cref="IsExpanded"/> bindable property.</summary>
    public static readonly BindableProperty<bool> IsExpandedProperty =
        BindableProperty.Register<TreeViewItem, bool>(
            nameof(IsExpanded),
            false,
            (s, o, n) => ((TreeViewItem)s).OnIsExpandedChanged(o, n)
        );

    /// <summary>Identifies the <see cref="IsSelected"/> bindable property.</summary>
    public static readonly BindableProperty<bool> IsSelectedProperty =
        BindableProperty.Register<TreeViewItem, bool>(
            nameof(IsSelected),
            false,
            (s, o, n) => ((TreeViewItem)s).OnIsSelectedChanged(o, n)
        );

    /// <summary>Gets or sets whether the child nodes are shown. Default <c>false</c>.</summary>
    public bool IsExpanded
    {
        get => GetValue(IsExpandedProperty);
        set => SetValue(IsExpandedProperty, value);
    }

    /// <summary>
    /// Gets or sets whether this node is the tree's selected node. Default <c>false</c>. Setting it selects or deselects
    /// the node in its <see cref="ParentTreeView"/>, updating <see cref="TreeView.SelectedItem"/>.
    /// </summary>
    public bool IsSelected
    {
        get => GetValue(IsSelectedProperty);
        set => SetValue(IsSelectedProperty, value);
    }

    /// <summary>Gets or sets the data item this node represents.</summary>
    public object? ItemValue { get; set; }

    /// <summary>Gets the tree this node belongs to, or <c>null</c> if it isn't part of one.</summary>
    public TreeView? ParentTreeView { get; internal set; }

    /// <summary>Gets the parent node, or <c>null</c> for a root node.</summary>
    public TreeViewItem? ParentTreeViewItem { get; internal set; }

    /// <summary>Gets the nesting depth: 0 for root nodes.</summary>
    public int Level { get; internal set; } = 0;

    /// <summary>
    /// Gets whether the node has (or, before its children are generated, will have) child nodes; controls the expander.
    /// </summary>
    public bool HasChildren { get; private set; } = false;

    /// <summary>Gets whether the pointer is over the header row.</summary>
    public bool IsHeaderHovered { get; internal set; } = false;

    /// <summary>
    /// Gets the child nodes. Reading it generates pending children from the children source. Use
    /// <see cref="AddChildItem"/> and <see cref="RemoveChildItem"/> to change manually built children.
    /// </summary>
    public IReadOnlyList<TreeViewItem> ChildrenItems
    {
        get
        {
            EnsureChildrenRealized();
            return _children;
        }
    }

    /// <summary>Occurs when the node is expanded.</summary>
    public event EventHandler? Expanded;

    /// <summary>Occurs when the node is collapsed.</summary>
    public event EventHandler? Collapsed;

    // Internal layout composition
    private readonly StackPanel _rootLayout;
    private readonly TreeViewItemHeader _headerRow;
    private readonly Border _indentSpacer;
    private readonly TreeViewExpanderButton _expanderButton;
    private readonly Icon _expanderIcon;
    private readonly Border _contentWrapper;
    private readonly StackPanel _childrenPanel;
    private readonly List<TreeViewItem> _children = [];

    private IEnumerable? _childrenSource;
    private WeakCollectionChangedSubscription<TreeViewItem>? _childrenSubscription;
    private bool _hasPendingChildren;

    // Used by TreeView.ResetNodes to find nodes that were not reused.
    internal bool ResetMark;

    internal List<TreeViewItem> RealizedChildren => _children;

    /// <summary>Gets the header row's rectangle in local coordinates (32 high before the first layout).</summary>
    public Rect HeaderBounds => new(0, 0, Bounds.Width, _headerRow.Bounds.Height > 0 ? _headerRow.Bounds.Height : 32f);

    /// <summary>Gets the header row's height.</summary>
    public float HeaderHeight => HeaderBounds.Height;

    /// <summary>Initializes a new node without content.</summary>
    public TreeViewItem()
    {
        IsFocusable = false; // TreeView itself manages focus and keyboard traversal
        CornerRadius = new CornerRadius(6);

        _rootLayout = new StackPanel { Orientation = Orientation.Vertical };

        _headerRow = new TreeViewItemHeader(this)
        {
            CornerRadius = CornerRadius,
            Padding = new Thickness(4, 2)
        };

        var headerStack = new StackPanel
        {
            Orientation = Orientation.Horizontal,
            Spacing = 4f,
            VerticalAlignment = VerticalAlignment.Center
        };

        _indentSpacer = new Border { Width = 0f, Height = 1f };

        _expanderIcon = new Icon(MaterialIconKind.ChevronRight, 18f)
        {
            VerticalAlignment = VerticalAlignment.Center,
            HorizontalAlignment = HorizontalAlignment.Center
        };

        _expanderButton = new TreeViewExpanderButton(this)
        {
            Width = 24f,
            Height = 24f,
            VerticalAlignment = VerticalAlignment.Center,
            Child = _expanderIcon
        };

        _contentWrapper = new Border
        {
            VerticalAlignment = VerticalAlignment.Center
        };

        headerStack.Add(_indentSpacer);
        headerStack.Add(_expanderButton);
        headerStack.Add(_contentWrapper);

        _headerRow.Child = headerStack;

        _childrenPanel = new StackPanel
        {
            Orientation = Orientation.Vertical,
            Visibility = Visibility.Collapsed
        };

        _rootLayout.Add(_headerRow);
        _rootLayout.Add(_childrenPanel);

        AddChild(_rootLayout);
        UpdateExpanderVisual();
    }

    /// <summary>Initializes a new node showing <paramref name="text"/>, which also becomes its <see cref="ItemValue"/>.</summary>
    /// <param name="text">The header text.</param>
    public TreeViewItem(string text) : this()
    {
        ItemValue = text;
        SetContentVisual(new TextBlock(text) { VerticalAlignment = VerticalAlignment.Center });
    }

    internal void UpdateIndentation()
    {
        float indent = ParentTreeView?.IndentSize ?? 20f;
        _indentSpacer.Width = Level * indent;
    }

    /// <summary>Sets the element shown in the header after the expander.</summary>
    /// <param name="visual">The header content.</param>
    public void SetContentVisual(UIElement visual)
    {
        _contentWrapper.Child = visual;
        InvalidateMeasure();
    }

    /// <summary>
    /// Sets the collection this node's children are generated from, replacing existing children. Children are created when
    /// the node is first expanded; an <see cref="INotifyCollectionChanged"/> source is observed weakly and applied
    /// incrementally.
    /// </summary>
    /// <param name="source">The child items, or <c>null</c> for none.</param>
    public void SetChildrenSource(IEnumerable? source)
    {
        _childrenSubscription?.Dispose();
        _childrenSubscription = null;

        DiscardChildren();

        _childrenSource = source;
        _hasPendingChildren = source != null;

        if (source is INotifyCollectionChanged incc)
        {
            _childrenSubscription = new WeakCollectionChangedSubscription<TreeViewItem>(
                incc, this, static (node, e) => node.OnChildrenCollectionChanged(e));
        }

        if (IsExpanded)
        {
            EnsureChildrenRealized();
        }
        UpdateHasChildren();
        InvalidateMeasure();
    }

    private void DiscardChildren()
    {
        if (_children.Count == 0) return;

        var tree = ParentTreeView;
        for (int i = 0; i < _children.Count; i++)
        {
            if (tree != null) tree.DiscardNode(_children[i]);
            else _children[i].Release();
        }
        _children.Clear();
        _childrenPanel.Clear();
    }

    private void OnChildrenCollectionChanged(NotifyCollectionChangedEventArgs e)
    {
        Atelier.Core.Threading.Dispatcher.VerifyAccess("TreeViewItem.Children collection change");

        var tree = ParentTreeView;
        if (!_hasPendingChildren && tree != null && _childrenSource != null)
        {
            tree.ApplyCollectionChange(_childrenSource, e, _children, _childrenPanel, this, Level + 1);
        }

        UpdateHasChildren();
    }

    private void EnsureChildrenRealized()
    {
        var tree = ParentTreeView;
        if (!_hasPendingChildren || tree == null || _childrenSource == null) return;

        _hasPendingChildren = false;
        foreach (var childObj in _childrenSource)
        {
            var childNode = tree.CreateTreeViewItem(childObj!, Level + 1, this);
            _children.Add(childNode);
            _childrenPanel.Add(childNode);
        }

        UpdateHasChildren();
        InvalidateMeasure();
    }

    /// <summary>
    /// Re-reads the children from the children source, keeping the nodes (and their state) of items that are still
    /// present. Does nothing without a children source or before the children were generated.
    /// </summary>
    public void RebuildChildren()
    {
        var tree = ParentTreeView;
        if (tree != null && _childrenSource != null && !_hasPendingChildren)
        {
            tree.ResetNodes(_childrenSource, _children, _childrenPanel, this, Level + 1, reuse: true);
            UpdateHasChildren();
            InvalidateMeasure();
        }
    }

    /// <summary>Appends a manually created child node (with its own children) to this node.</summary>
    /// <param name="child">The node to add.</param>
    public void AddChildItem(TreeViewItem child)
    {
        EnsureChildrenRealized();
        _children.Add(child);
        _childrenPanel.Add(child);
        child.AttachToTree(ParentTreeView, this, Level + 1);

        UpdateHasChildren();
        InvalidateMeasure();
    }

    /// <summary>Removes a child node; clears the tree's selection if it was inside that child.</summary>
    /// <param name="child">The node to remove.</param>
    public void RemoveChildItem(TreeViewItem child)
    {
        int index = _children.IndexOf(child);
        if (index < 0) return;

        _children.RemoveAt(index);
        _childrenPanel.Remove(child);
        ParentTreeView?.OnNodeRemoved(child);
        child.AttachToTree(null, null, 0);

        UpdateHasChildren();
        InvalidateMeasure();
    }

    // Links this node and its generated subtree to a tree position.
    internal void AttachToTree(TreeView? tree, TreeViewItem? parent, int level)
    {
        ParentTreeView = tree;
        ParentTreeViewItem = parent;
        Level = level;
        UpdateIndentation();

        if (tree != null && IsExpanded)
        {
            EnsureChildrenRealized();
        }
        UpdateHasChildren();

        for (int i = 0; i < _children.Count; i++)
        {
            _children[i].AttachToTree(tree, this, level + 1);
        }

        if (tree != null && IsSelected)
        {
            tree.AdoptSelectedNode(this);
        }
    }

    // The node was discarded by its tree: stop observing model collections so nothing keeps it (or the tree) alive.
    internal void Release()
    {
        _childrenSubscription?.Dispose();
        _childrenSubscription = null;

        for (int i = 0; i < _children.Count; i++)
        {
            _children[i].Release();
        }

        ParentTreeView = null;
        ParentTreeViewItem = null;
    }

    internal bool IsSelfOrAncestorOf(TreeViewItem node)
    {
        for (var current = node; current != null; current = current.ParentTreeViewItem)
        {
            if (current == this) return true;
        }
        return false;
    }

    private void UpdateHasChildren()
    {
        HasChildren = _hasPendingChildren ? SourceHasItems(_childrenSource) : _children.Count > 0;
        UpdateExpanderVisual();
    }

    private static bool SourceHasItems(IEnumerable? source)
    {
        switch (source)
        {
            case null:
                return false;
            case ICollection collection:
                return collection.Count > 0;
            default:
                var enumerator = source.GetEnumerator();
                try
                {
                    return enumerator.MoveNext();
                }
                finally
                {
                    (enumerator as IDisposable)?.Dispose();
                }
        }
    }

    internal void UpdateExpanderVisual()
    {
        if (HasChildren)
        {
            _expanderIcon.Visibility = Visibility.Visible;
            _expanderIcon.Kind = IsExpanded
                ? (ParentTreeView?.ExpandIcon ?? MaterialIconKind.ExpandMore)
                : (ParentTreeView?.CollapseIcon ?? MaterialIconKind.ChevronRight);
            _expanderIcon.Size = ParentTreeView?.IconSize ?? 18f;
        }
        else
        {
            _expanderIcon.Visibility = Visibility.Collapsed;
        }
    }

    private void OnIsExpandedChanged(bool oldVal, bool newVal)
    {
        if (newVal)
        {
            EnsureChildrenRealized();
        }

        _childrenPanel.Visibility = newVal ? Visibility.Visible : Visibility.Collapsed;
        UpdateExpanderVisual();
        InvalidateMeasure();

        if (newVal)
        {
            Expanded?.Invoke(this, EventArgs.Empty);
            ParentTreeView?.NotifyItemExpanded(this);
        }
        else
        {
            Collapsed?.Invoke(this, EventArgs.Empty);
            ParentTreeView?.NotifyItemCollapsed(this);
        }
    }

    private void OnIsSelectedChanged(bool oldVal, bool newVal)
    {
        InvalidateVisual();

        var tree = ParentTreeView;
        if (tree != null && !tree.IsSyncingSelection)
        {
            tree.OnNodeIsSelectedChanged(this, newVal);
        }
    }

    internal void SelectThis()
    {
        ParentTreeView?.SelectFromPointer(this);
    }

    /// <summary>Expands all ancestors of this node so it is shown.</summary>
    public void EnsureVisible()
    {
        var current = ParentTreeViewItem;
        while (current != null)
        {
            current.IsExpanded = true;
            current = current.ParentTreeViewItem;
        }
    }

    /// <inheritdoc/>
    protected override Size MeasureOverride(Size availableSize)
    {
        _rootLayout.Measure(availableSize);
        return _rootLayout.DesiredSize;
    }

    /// <inheritdoc/>
    protected override Size ArrangeOverride(Size finalSize)
    {
        _rootLayout.Arrange(new Rect(Point.Zero, finalSize));
        return finalSize;
    }
}

internal class TreeViewItemHeader(TreeViewItem owner) : Border
{
    public override UIElement? HitTest(Point point)
    {
        if (Visibility != Visibility.Visible || !IsHitTestVisible || !Bounds.Contains(point))
        {
            return null;
        }

        Point localPoint = point.Offset(-Bounds.X, -Bounds.Y);
        for (int i = Children.Count - 1; i >= 0; i--)
        {
            if (Children[i] is UIElement child)
            {
                var hit = child.HitTest(localPoint);
                if (hit is TreeViewExpanderButton)
                {
                    return hit;
                }
            }
        }

        return this;
    }

    public override void OnPointerEntered(PointerEventArgs e)
    {
        base.OnPointerEntered(e);
        owner.IsHeaderHovered = true;
        owner.InvalidateVisual();
    }

    public override void OnPointerExited(PointerEventArgs e)
    {
        base.OnPointerExited(e);
        owner.IsHeaderHovered = false;
        owner.InvalidateVisual();
    }

    public override void OnPointerPressed(PointerEventArgs e)
    {
        base.OnPointerPressed(e);
        if (e.Button == PointerButtons.Left)
        {
            e.Handled = true;
        }
    }

    public override void OnPointerReleased(PointerEventArgs e)
    {
        base.OnPointerReleased(e);
        if (e.Button != PointerButtons.Left)
        {
            return;
        }

        e.Handled = true;

        // The platform reports consecutive clicks; every second one is a double click.
        if (e.ClickCount >= 2 && e.ClickCount % 2 == 0)
        {
            if (owner.HasChildren)
            {
                owner.IsExpanded = !owner.IsExpanded;
            }
        }
        else
        {
            owner.SelectThis();
        }
    }
}

internal class TreeViewExpanderButton(TreeViewItem owner) : Border
{
    public override UIElement? HitTest(Point point)
    {
        if (Visibility != Visibility.Visible || !IsHitTestVisible || !Bounds.Contains(point))
        {
            return null;
        }
        return this;
    }

    public override void OnPointerPressed(PointerEventArgs e)
    {
        base.OnPointerPressed(e);
        if (e.Button == PointerButtons.Left)
        {
            e.Handled = true;
        }
    }

    public override void OnPointerReleased(PointerEventArgs e)
    {
        base.OnPointerReleased(e);
        if (e.Button != PointerButtons.Left)
        {
            return;
        }

        e.Handled = true;
        if (owner.HasChildren)
        {
            owner.IsExpanded = !owner.IsExpanded;
        }
    }
}
