using System;
using System.Collections.Generic;
using System.ComponentModel;
using Atelier.Core.Events;
using Atelier.Core.Inspection;
using Atelier.Core.Primitives;
using Atelier.Core.Properties;
using Atelier.Core.Tree;
using Atelier.Layout;

namespace Atelier.Controls;

/// <summary>
/// A Native AOT compatible property inspector and editor. Properties are read from the <see cref="IInspectableObject"/>
/// descriptors of <see cref="SelectedObject"/> (typically generated by <see cref="InspectableAttribute"/>), so the
/// inspected object's members are never reflected over.
/// </summary>
/// <remarks>
/// <para>
/// Rows and editors are created once per <see cref="SelectedObject"/>. Filtering, sorting, expanding categories and
/// changing <see cref="LabelWidth"/> reuse them. Editors are created by <see cref="EditorRegistry"/>.
/// </para>
/// <para>
/// Editors reflect external changes: while the grid is attached to a visual tree it listens to
/// <see cref="INotifyPropertyChanged.PropertyChanged"/> of the selected object (the subscription is removed when the
/// object is replaced or the grid is detached). Objects without change notification are re-read after every edit made
/// through the grid, and <see cref="Refresh"/> re-reads all values on demand. Notifications raised on other threads are
/// applied on the UI thread.
/// </para>
/// <para>
/// Exceptions thrown by property getters and setters are caught: the row shows the message and
/// <see cref="PropertyValueError"/> is raised.
/// </para>
/// </remarks>
public class PropertyGrid : Control
{
    private const string DefaultCategory = "General";

    private static readonly Color s_mutedText = Color.FromRgb(0x88, 0x88, 0x88);
    private static readonly Color s_readOnlyText = Color.FromRgb(0x9E, 0x9E, 0x9E);
    private static readonly Color s_toolbarBorder = Color.Black.WithAlpha(0.08f);
    private static readonly Color s_rootBorder = Color.Black.WithAlpha(0.12f);
    private static readonly Color s_headerBackground = Color.Black.WithAlpha(0.04f);
    private static readonly Color s_headerBorder = Color.Black.WithAlpha(0.06f);
    private static readonly Color s_rowBorder = Color.Black.WithAlpha(0.04f);
    private static readonly Color s_rowHover = Color.Black.WithAlpha(0.02f);
    private static readonly Color s_descriptionBackground = Color.Black.WithAlpha(0.03f);
    private static readonly Color s_errorText = Color.FromRgb(0xC6, 0x28, 0x28);
    private static readonly Color s_errorBackground = Color.FromRgb(0xC6, 0x28, 0x28).WithAlpha(0.08f);

    private static readonly Comparison<CategoryGroup> s_groupComparison =
        static (a, b) => StringComparer.OrdinalIgnoreCase.Compare(a.Name, b.Name);

    private static readonly Comparison<PropertyRow> s_alphabeticalComparison = static (a, b) =>
    {
        int result = StringComparer.OrdinalIgnoreCase.Compare(a.DisplayName, b.DisplayName);
        return result != 0 ? result : a.Index.CompareTo(b.Index);
    };

    #region Bindable Properties

    /// <summary>Identifies the <see cref="SelectedObject"/> bindable property.</summary>
    public static readonly BindableProperty<object?> SelectedObjectProperty =
        BindableProperty.Register<PropertyGrid, object?>(
            nameof(SelectedObject),
            null,
            (s, o, n) => ((PropertyGrid)s).OnSelectedObjectChanged(o, n)
        );

    /// <summary>Identifies the <see cref="SortMode"/> bindable property.</summary>
    public static readonly BindableProperty<PropertySortMode> SortModeProperty =
        BindableProperty.Register<PropertyGrid, PropertySortMode>(
            nameof(SortMode),
            PropertySortMode.Categorized,
            (s, o, n) => ((PropertyGrid)s).OnSortModeChanged(o, n)
        );

    /// <summary>Identifies the <see cref="FilterText"/> bindable property.</summary>
    public static readonly BindableProperty<string> FilterTextProperty =
        BindableProperty.Register<PropertyGrid, string>(
            nameof(FilterText),
            string.Empty,
            (s, o, n) => ((PropertyGrid)s).OnFilterTextChanged(o, n)
        );

    /// <summary>Identifies the <see cref="IsToolbarVisible"/> bindable property.</summary>
    public static readonly BindableProperty<bool> IsToolbarVisibleProperty =
        BindableProperty.Register<PropertyGrid, bool>(
            nameof(IsToolbarVisible),
            true,
            (s, o, n) => ((PropertyGrid)s).OnIsToolbarVisibleChanged(o, n)
        );

    /// <summary>Identifies the <see cref="ToolbarElevation"/> bindable property.</summary>
    public static readonly BindableProperty<float> ToolbarElevationProperty =
        BindableProperty.Register<PropertyGrid, float>(
            nameof(ToolbarElevation),
            2f,
            (s, o, n) => ((PropertyGrid)s).OnToolbarElevationChanged(o, n)
        );

    /// <summary>Identifies the <see cref="LabelWidth"/> bindable property.</summary>
    public static readonly BindableProperty<float> LabelWidthProperty =
        BindableProperty.Register<PropertyGrid, float>(
            nameof(LabelWidth),
            160f,
            (s, o, n) => ((PropertyGrid)s).OnLabelWidthChanged(n),
            validateValue: static w => float.IsFinite(w) && w >= 0
        );

    /// <summary>Identifies the <see cref="IsDescriptionVisible"/> bindable property.</summary>
    public static readonly BindableProperty<bool> IsDescriptionVisibleProperty =
        BindableProperty.Register<PropertyGrid, bool>(
            nameof(IsDescriptionVisible),
            true,
            (s, o, n) => ((PropertyGrid)s).UpdateDescriptionPanel()
        );

    #endregion

    #region Properties

    /// <summary>
    /// Gets or sets the inspected object. Its properties are listed when it implements <see cref="IInspectableObject"/>.
    /// Changing it recreates the rows and scrolls back to the top.
    /// </summary>
    public object? SelectedObject
    {
        get => GetValue(SelectedObjectProperty);
        set => SetValue(SelectedObjectProperty, value);
    }

    /// <summary>
    /// Gets or sets whether properties are grouped by category or listed alphabetically. The default is
    /// <see cref="PropertySortMode.Categorized"/>.
    /// </summary>
    public PropertySortMode SortMode
    {
        get => GetValue(SortModeProperty);
        set => SetValue(SortModeProperty, value);
    }

    /// <summary>
    /// Gets or sets the text that filters rows (case-insensitive match on display name, name or category; surrounding
    /// white space is ignored). While a filter is active, categories with matches are expanded.
    /// </summary>
    public string FilterText
    {
        get => GetValue(FilterTextProperty);
        set => SetValue(FilterTextProperty, value);
    }

    /// <summary>
    /// Gets or sets whether the toolbar with the sort buttons and filter box is shown. The default is <see langword="true"/>.
    /// </summary>
    public bool IsToolbarVisible
    {
        get => GetValue(IsToolbarVisibleProperty);
        set => SetValue(IsToolbarVisibleProperty, value);
    }

    /// <summary>
    /// Gets or sets the elevation (shadow depth) of the toolbar. The default is 2.
    /// </summary>
    public float ToolbarElevation
    {
        get => GetValue(ToolbarElevationProperty);
        set => SetValue(ToolbarElevationProperty, value);
    }

    /// <summary>
    /// Gets or sets the width of the label column in pixels. The default is 160; must be finite and not negative.
    /// </summary>
    public float LabelWidth
    {
        get => GetValue(LabelWidthProperty);
        set => SetValue(LabelWidthProperty, value);
    }

    /// <summary>
    /// Gets or sets whether the description panel below the rows is shown. It appears only when a property of the
    /// selected object has a <see cref="IPropertyDescriptor.Description"/>, and describes the row last hovered, clicked
    /// or focused. The default is <see langword="true"/>.
    /// </summary>
    public bool IsDescriptionVisible
    {
        get => GetValue(IsDescriptionVisibleProperty);
        set => SetValue(IsDescriptionVisibleProperty, value);
    }

    /// <summary>
    /// Gets the internal toolbar control for customization or direct inspection.
    /// </summary>
    public Toolbar Toolbar => _toolbar;

    /// <summary>
    /// Gets the per-instance editor registry for registering custom or overriding built-in editors. Registering an
    /// editor recreates the grid's rows.
    /// </summary>
    public PropertyEditorRegistry EditorRegistry { get; } = new();

    #endregion

    #region Events

    /// <summary>
    /// Raised when a property value is modified through an editor within this PropertyGrid.
    /// </summary>
    public event EventHandler<PropertyValueChangedEventArgs>? PropertyValueChanged;

    /// <summary>
    /// Raised before an editor sets a property; set <see cref="PropertyValueChangingEventArgs.Cancel"/> to reject the
    /// change (the editor then shows the current value again).
    /// </summary>
    public event EventHandler<PropertyValueChangingEventArgs>? PropertyValueChanging;

    /// <summary>
    /// Raised when a property getter or setter throws. The exception is caught and its message is shown on the row.
    /// </summary>
    public event EventHandler<PropertyValueErrorEventArgs>? PropertyValueError;

    /// <summary>
    /// Raised when the <see cref="SelectedObject"/> changes.
    /// </summary>
    public event EventHandler<object?>? SelectedObjectChanged;

    /// <summary>
    /// Raised when the <see cref="SortMode"/> changes.
    /// </summary>
    public event EventHandler<PropertySortMode>? SortModeChanged;

    /// <summary>
    /// Raised when the <see cref="FilterText"/> changes.
    /// </summary>
    public event EventHandler<string>? FilterTextChanged;

    #endregion

    #region Fields

    private readonly Border _rootBorder;
    private readonly Grid _rootLayout;
    private readonly Toolbar _toolbar;
    private readonly Button _categorizedBtn;
    private readonly Button _alphabeticalBtn;
    private readonly TextBox _filterTextBox;
    private readonly ScrollViewer _scrollViewer;
    private readonly StackPanel _contentPanel;
    private readonly Border _placeholder;
    private readonly TextBlock _placeholderText;
    private readonly Border _descriptionPanel;
    private readonly TextBlock _descriptionTitle;
    private readonly TextBlock _descriptionText;

    // Rows are built once per SelectedObject and reused by filtering, sorting and expansion.
    private readonly List<PropertyRow> _rows = [];
    private readonly Dictionary<string, PropertyRow> _rowsByName = new(StringComparer.Ordinal);
    private readonly List<CategoryGroup> _groups = [];
    private readonly Dictionary<string, CategoryGroup> _groupsByName = new(StringComparer.OrdinalIgnoreCase);
    private readonly List<PropertyRow> _alphabeticalRows = [];
    private bool _isAlphabeticalSorted;

    private readonly Dictionary<string, bool> _categoryExpansionState = new(StringComparer.OrdinalIgnoreCase);
    private string _activeFilter = string.Empty;
    private bool _isUpdatingFilterText;
    private bool _hasDescriptions;
    private PropertyRow? _activeRow;

    private INotifyPropertyChanged? _observedTarget;
    private readonly PropertyChangedEventHandler _targetPropertyChangedHandler;
    private readonly EventHandler<PointerEventArgs> _rowPointerEnteredHandler;
    private readonly EventHandler<PointerEventArgs> _rowPointerExitedHandler;
    private readonly EventHandler<PointerEventArgs> _rowPointerPressedHandler;
    private readonly EventHandler<PointerEventArgs> _headerPointerPressedHandler;
    private readonly EventHandler _editorGotFocusHandler;

    #endregion

    /// <summary>
    /// Initializes a new property grid with no selected object.
    /// </summary>
    public PropertyGrid()
    {
        IsFocusable = true;

        _targetPropertyChangedHandler = OnTargetPropertyChanged;
        _rowPointerEnteredHandler = OnRowPointerEntered;
        _rowPointerExitedHandler = OnRowPointerExited;
        _rowPointerPressedHandler = OnRowPointerPressed;
        _headerPointerPressedHandler = OnHeaderPointerPressed;
        _editorGotFocusHandler = OnEditorGotFocus;

        // Toolbar buttons
        var catContent = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 6, VerticalAlignment = VerticalAlignment.Center };
        catContent.Add(new Icon { Kind = MaterialIconKind.Category, Size = 16, VerticalAlignment = VerticalAlignment.Center });
        catContent.Add(new TextBlock("Categorized") { FontSize = 12, VerticalAlignment = VerticalAlignment.Center });

        _categorizedBtn = new Button
        {
            Variant = ButtonVariant.Tonal,
            Padding = new Thickness(10, 6),
            CornerRadius = new CornerRadius(16),
            VerticalAlignment = VerticalAlignment.Center,
            Content = catContent
        };
        _categorizedBtn.Click += (s, e) => SortMode = PropertySortMode.Categorized;

        var alphaContent = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 6, VerticalAlignment = VerticalAlignment.Center };
        alphaContent.Add(new Icon { Kind = MaterialIconKind.SortByAlpha, Size = 16, VerticalAlignment = VerticalAlignment.Center });
        alphaContent.Add(new TextBlock("Alphabetical") { FontSize = 12, VerticalAlignment = VerticalAlignment.Center });

        _alphabeticalBtn = new Button
        {
            Variant = ButtonVariant.Text,
            Padding = new Thickness(10, 6),
            CornerRadius = new CornerRadius(16),
            VerticalAlignment = VerticalAlignment.Center,
            Content = alphaContent
        };
        _alphabeticalBtn.Click += (s, e) => SortMode = PropertySortMode.Alphabetical;

        var buttonGroup = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 6, VerticalAlignment = VerticalAlignment.Center };
        buttonGroup.Add(_categorizedBtn);
        buttonGroup.Add(_alphabeticalBtn);

        // Filter text box
        _filterTextBox = new TextBox
        {
            Placeholder = "Filter properties...",
            Height = 32,
            CornerRadius = new CornerRadius(16),
            Padding = new Thickness(12, 4),
            Margin = new Thickness(10, 0, 0, 0),
            VerticalAlignment = VerticalAlignment.Center
        };
        _filterTextBox.TextChanged += (s, text) =>
        {
            if (_isUpdatingFilterText) return;
            _isUpdatingFilterText = true;
            try
            {
                FilterText = text;
            }
            finally
            {
                _isUpdatingFilterText = false;
            }
        };

        // Toolbar Grid: Col 0 = Toggle Buttons (Auto), Col 1 = Filter (Star)
        var toolbarGrid = new Grid();
        toolbarGrid.RowDefinitions.Add(new RowDefinition(GridLength.Auto));
        toolbarGrid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Auto));
        toolbarGrid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));

        Grid.SetColumn(buttonGroup, 0);
        Grid.SetColumn(_filterTextBox, 1);

        toolbarGrid.Add(buttonGroup);
        toolbarGrid.Add(_filterTextBox);

        _toolbar = new Toolbar
        {
            Elevation = ToolbarElevation,
            Padding = new Thickness(10, 8),
            BorderThickness = new Thickness(0, 0, 0, 1),
            BorderBrush = s_toolbarBorder,
            CornerRadius = new CornerRadius(8, 8, 0, 0),
            Content = toolbarGrid
        };

        // Properties container & scroll viewer
        _contentPanel = new StackPanel
        {
            Orientation = Orientation.Vertical,
            Spacing = 0
        };

        _scrollViewer = new ScrollViewer
        {
            Content = _contentPanel,
            HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled,
            VerticalScrollBarVisibility = ScrollBarVisibility.Auto
        };

        // Message shown over the (empty) content area: no object, no properties or no filter matches.
        _placeholderText = new TextBlock(string.Empty)
        {
            FontSize = 12,
            Foreground = s_mutedText
        };
        _placeholder = new Border
        {
            Padding = new Thickness(32),
            HorizontalAlignment = HorizontalAlignment.Center,
            VerticalAlignment = VerticalAlignment.Top,
            Visibility = Visibility.Collapsed,
            Child = _placeholderText
        };

        // Description panel: describes the row last hovered, clicked or focused.
        _descriptionTitle = new TextBlock(string.Empty) { FontSize = 12, Bold = true };
        _descriptionText = new TextBlock(string.Empty)
        {
            FontSize = 11,
            Foreground = s_mutedText,
            TextWrapping = TextWrapping.Wrap
        };
        var descriptionStack = new StackPanel { Orientation = Orientation.Vertical, Spacing = 2 };
        descriptionStack.Add(_descriptionTitle);
        descriptionStack.Add(_descriptionText);
        _descriptionPanel = new Border
        {
            Padding = new Thickness(12, 8),
            MinHeight = 56,
            BorderThickness = new Thickness(0, 1, 0, 0),
            BorderBrush = s_toolbarBorder,
            Background = s_descriptionBackground,
            Visibility = Visibility.Collapsed,
            Child = descriptionStack
        };

        // Root layout: Row 0 = Toolbar (Auto), Row 1 = Content (Star), Row 2 = Description (Auto)
        _rootLayout = new Grid();
        _rootLayout.RowDefinitions.Add(new RowDefinition(GridLength.Auto));
        _rootLayout.RowDefinitions.Add(new RowDefinition(GridLength.Star));
        _rootLayout.RowDefinitions.Add(new RowDefinition(GridLength.Auto));

        Grid.SetRow(_toolbar, 0);
        Grid.SetRow(_scrollViewer, 1);
        Grid.SetRow(_placeholder, 1);
        Grid.SetRow(_descriptionPanel, 2);

        // Add ScrollViewer first, then Toolbar so Toolbar renders on top
        // and its elevation drop shadow casts downward over the scrolling properties.
        _rootLayout.Add(_scrollViewer);
        _rootLayout.Add(_toolbar);
        _rootLayout.Add(_placeholder);
        _rootLayout.Add(_descriptionPanel);

        _rootBorder = new Border
        {
            BorderThickness = new Thickness(1),
            BorderBrush = s_rootBorder,
            CornerRadius = new CornerRadius(8),
            Background = Color.Transparent,
            ClipToBounds = true,
            Child = _rootLayout
        };

        AddChild(_rootBorder);

        // The registry is owned by this grid (same lifetime), so this subscription cannot leak.
        EditorRegistry.Changed += OnEditorRegistryChanged;

        BuildRows(resetScroll: true);
    }

    #region Custom Editor API

    /// <summary>
    /// Registers a custom editor factory for property type <typeparamref name="T"/> on this PropertyGrid and recreates
    /// the rows.
    /// </summary>
    /// <typeparam name="T">The property type edited by the factory's editors.</typeparam>
    /// <param name="factory">Creates the editor for a property.</param>
    public void RegisterEditor<T>(Func<PropertyEditorContext, UIElement> factory) =>
        EditorRegistry.Register<T>(factory);

    /// <summary>
    /// Registers a custom editor factory for the specified property type on this PropertyGrid and recreates the rows.
    /// </summary>
    /// <param name="type">The property type edited by the factory's editors.</param>
    /// <param name="factory">Creates the editor for a property.</param>
    public void RegisterEditor(Type type, Func<PropertyEditorContext, UIElement> factory) =>
        EditorRegistry.Register(type, factory);

    /// <summary>
    /// Registers a custom editor factory with a predicate selector on this PropertyGrid and recreates the rows.
    /// </summary>
    /// <param name="predicate">Returns <see langword="true"/> for the properties the factory handles.</param>
    /// <param name="factory">Creates the editor for a property.</param>
    public void RegisterEditor(Func<PropertyEditorContext, bool> predicate, Func<PropertyEditorContext, UIElement> factory) =>
        EditorRegistry.Register(predicate, factory);

    private void OnEditorRegistryChanged()
    {
        if (_rows.Count > 0)
        {
            BuildRows(resetScroll: false);
        }
    }

    #endregion

    #region Expand / Collapse Control

    /// <summary>
    /// Expands every category of the selected object.
    /// </summary>
    public void ExpandAll() => SetAllExpanded(true);

    /// <summary>
    /// Collapses every category of the selected object.
    /// </summary>
    public void CollapseAll() => SetAllExpanded(false);

    /// <summary>
    /// Expands or collapses a category. The state is remembered by name across selected objects.
    /// </summary>
    /// <param name="category">The category name (case-insensitive).</param>
    /// <param name="isExpanded">Whether the category is expanded.</param>
    /// <exception cref="ArgumentNullException"><paramref name="category"/> is <see langword="null"/>.</exception>
    public void SetCategoryExpanded(string category, bool isExpanded)
    {
        ArgumentNullException.ThrowIfNull(category);
        _categoryExpansionState[category] = isExpanded;
        if (_groupsByName.TryGetValue(category, out CategoryGroup? group))
        {
            group.CollapsedWhileFiltering = !isExpanded;
            UpdateGroupExpansion(group);
        }
    }

    /// <summary>
    /// Gets whether a category is currently displayed expanded (while a filter is active, categories are expanded
    /// unless collapsed during the filter).
    /// </summary>
    /// <param name="category">The category name (case-insensitive).</param>
    /// <returns><see langword="true"/> if the category exists and is expanded.</returns>
    public bool IsCategoryExpanded(string category) =>
        category != null && _groupsByName.TryGetValue(category, out CategoryGroup? group) && group.IsExpanded;

    private void SetAllExpanded(bool isExpanded)
    {
        for (int i = 0; i < _groups.Count; i++)
        {
            CategoryGroup group = _groups[i];
            _categoryExpansionState[group.Name] = isExpanded;
            group.CollapsedWhileFiltering = !isExpanded;
            UpdateGroupExpansion(group);
        }
    }

    private void UpdateGroupExpansion(CategoryGroup group)
    {
        bool expanded = _activeFilter.Length > 0
            ? !group.CollapsedWhileFiltering
            : !_categoryExpansionState.TryGetValue(group.Name, out bool stored) || stored;

        group.IsExpanded = expanded;
        group.Chevron.Kind = expanded ? MaterialIconKind.ExpandMore : MaterialIconKind.ChevronRight;
        group.ItemsPanel.Visibility = expanded && group.VisibleCount > 0 ? Visibility.Visible : Visibility.Collapsed;
    }

    private void OnHeaderPointerPressed(object? sender, PointerEventArgs e)
    {
        if (sender is not CategoryHeader header) return;

        // Toggle what is displayed: with a filter active, categories are shown expanded regardless of the stored state.
        CategoryGroup group = header.Group;
        bool expand = !group.IsExpanded;
        if (_activeFilter.Length > 0)
        {
            group.CollapsedWhileFiltering = !expand;
        }
        else
        {
            _categoryExpansionState[group.Name] = expand;
        }
        UpdateGroupExpansion(group);
        e.Handled = true;
    }

    #endregion

    #region Change Notifications

    private void OnSelectedObjectChanged(object? oldObj, object? newObj)
    {
        SelectedObjectChanged?.Invoke(this, newObj);
        BuildRows(resetScroll: true);
    }

    private void OnSortModeChanged(PropertySortMode oldMode, PropertySortMode newMode)
    {
        _categorizedBtn.Variant = newMode == PropertySortMode.Categorized ? ButtonVariant.Tonal : ButtonVariant.Text;
        _alphabeticalBtn.Variant = newMode == PropertySortMode.Alphabetical ? ButtonVariant.Tonal : ButtonVariant.Text;
        SortModeChanged?.Invoke(this, newMode);
        ArrangeRows();
    }

    private void OnFilterTextChanged(string oldText, string newText)
    {
        if (!_isUpdatingFilterText && _filterTextBox.Text != newText)
        {
            _isUpdatingFilterText = true;
            try
            {
                _filterTextBox.Text = newText ?? string.Empty;
            }
            finally
            {
                _isUpdatingFilterText = false;
            }
        }

        FilterTextChanged?.Invoke(this, newText);
        ApplyFilter(force: false);
    }

    private void OnIsToolbarVisibleChanged(bool oldVal, bool newVal) =>
        _toolbar.Visibility = newVal ? Visibility.Visible : Visibility.Collapsed;

    private void OnToolbarElevationChanged(float oldVal, float newVal) =>
        _toolbar.Elevation = newVal;

    private void OnLabelWidthChanged(float width)
    {
        GridLength length = GridLength.Pixels(width);
        for (int i = 0; i < _rows.Count; i++)
        {
            _rows[i].LabelColumn.Width = length;
        }
    }

    internal bool RaisePropertyValueChanging(object target, IPropertyDescriptor property, object? oldValue, object? newValue)
    {
        var handler = PropertyValueChanging;
        if (handler == null) return true;

        var args = new PropertyValueChangingEventArgs(target, property, oldValue, newValue);
        handler(this, args);
        return !args.Cancel;
    }

    internal void RaisePropertyValueError(object target, IPropertyDescriptor property, Exception exception, object? attemptedValue, bool isReadError) =>
        PropertyValueError?.Invoke(this, new PropertyValueErrorEventArgs(target, property, exception, attemptedValue, isReadError));

    internal void OnValueCommitted(PropertyEditorContext context, object? oldValue, object? newValue)
    {
        PropertyValueChanged?.Invoke(this, new PropertyValueChangedEventArgs(context.Target, context.Descriptor, oldValue, newValue));

        // Without change notifications, re-read the other rows so derived properties stay current.
        if (_observedTarget == null)
        {
            for (int i = 0; i < _rows.Count; i++)
            {
                PropertyEditorContext other = _rows[i].Context;
                if (!ReferenceEquals(other, context))
                {
                    other.Refresh();
                }
            }
        }
    }

    #endregion

    #region Refresh & change tracking

    /// <summary>
    /// Re-reads every property of the selected object and updates editors whose value changed. Use it after changing
    /// an object that does not implement <see cref="INotifyPropertyChanged"/>.
    /// </summary>
    public void Refresh()
    {
        for (int i = 0; i < _rows.Count; i++)
        {
            _rows[i].Context.Refresh();
        }
    }

    /// <inheritdoc/>
    protected override void OnAttachedToVisualTree()
    {
        base.OnAttachedToVisualTree();
        StartObservingTarget();
        Refresh(); // changes made while detached were not observed
    }

    /// <inheritdoc/>
    protected override void OnDetachedFromVisualTree()
    {
        StopObservingTarget();
        base.OnDetachedFromVisualTree();
    }

    private void StartObservingTarget()
    {
        if (_observedTarget == null && SelectedObject is INotifyPropertyChanged notifier)
        {
            notifier.PropertyChanged += _targetPropertyChangedHandler;
            _observedTarget = notifier;
        }
    }

    private void StopObservingTarget()
    {
        if (_observedTarget != null)
        {
            _observedTarget.PropertyChanged -= _targetPropertyChangedHandler;
            _observedTarget = null;
        }
    }

    private void OnTargetPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        // Like bindings, accept notifications from background work and apply them on the UI thread.
        if (!Atelier.Core.Threading.Dispatcher.CheckAccess())
        {
            Atelier.Core.Threading.Dispatcher.Post(() => OnTargetPropertyChanged(sender, e));
            return;
        }

        string? name = e.PropertyName;
        if (string.IsNullOrEmpty(name))
        {
            Refresh();
        }
        else if (_rowsByName.TryGetValue(name, out PropertyRow? row))
        {
            row.Context.Refresh();
        }
    }

    #endregion

    #region Row building

    /// <summary>
    /// Recreates all rows and editors from the descriptors of <see cref="SelectedObject"/>, keeping the scroll
    /// position. Needed only when the set of properties or the editors change; value changes are picked up by
    /// <see cref="Refresh"/>.
    /// </summary>
    public void RebuildProperties() => BuildRows(resetScroll: false);

    private void BuildRows(bool resetScroll)
    {
        StopObservingTarget();

        _contentPanel.Clear();
        _rows.Clear();
        _rowsByName.Clear();
        _groups.Clear();
        _groupsByName.Clear();
        _alphabeticalRows.Clear();
        _isAlphabeticalSorted = false;
        _activeRow = null;
        _hasDescriptions = false;

        object? target = SelectedObject;
        if (target != null)
        {
            IReadOnlyList<IPropertyDescriptor> properties = ObjectInspector.GetProperties(target);
            for (int i = 0; i < properties.Count; i++)
            {
                IPropertyDescriptor descriptor = properties[i];
                if (descriptor == null) continue;

                string category = string.IsNullOrWhiteSpace(descriptor.Category) ? DefaultCategory : descriptor.Category;
                if (!_groupsByName.TryGetValue(category, out CategoryGroup? group))
                {
                    group = CreateGroup(category);
                    _groupsByName.Add(category, group);
                    _groups.Add(group);
                }

                var row = CreateRow(descriptor, target, _rows.Count);
                group.Rows.Add(row);
                _rows.Add(row);
                _rowsByName.TryAdd(descriptor.Name ?? string.Empty, row);
                if (!string.IsNullOrEmpty(descriptor.Description))
                {
                    _hasDescriptions = true;
                }
            }

            _groups.Sort(s_groupComparison);
        }

        ArrangeRows();
        ApplyFilter(force: true);
        UpdateDescriptionPanel();

        if (resetScroll)
        {
            _scrollViewer.ScrollOffsetY = 0;
        }

        if (IsAttachedToVisualTree)
        {
            StartObservingTarget();
        }
    }

    // Places the existing rows for the current sort mode: category headers with their rows, or one alphabetical list.
    private void ArrangeRows()
    {
        _contentPanel.Clear();

        if (SortMode == PropertySortMode.Alphabetical)
        {
            for (int i = 0; i < _groups.Count; i++)
            {
                _groups[i].ItemsPanel.Clear();
            }

            if (!_isAlphabeticalSorted)
            {
                _alphabeticalRows.Clear();
                _alphabeticalRows.AddRange(_rows);
                _alphabeticalRows.Sort(s_alphabeticalComparison);
                _isAlphabeticalSorted = true;
            }

            for (int i = 0; i < _alphabeticalRows.Count; i++)
            {
                _contentPanel.Add(_alphabeticalRows[i]);
            }
        }
        else
        {
            for (int i = 0; i < _groups.Count; i++)
            {
                CategoryGroup group = _groups[i];
                if (group.ItemsPanel.Children.Count == 0)
                {
                    for (int j = 0; j < group.Rows.Count; j++)
                    {
                        group.ItemsPanel.Add(group.Rows[j]);
                    }
                }
                _contentPanel.Add(group.Header);
                _contentPanel.Add(group.ItemsPanel);
            }
        }
    }

    // Shows the rows matching FilterText and updates category counts and the placeholder; creates nothing per row.
    private void ApplyFilter(bool force)
    {
        string filter = (FilterText ?? string.Empty).Trim();
        if (!force && string.Equals(filter, _activeFilter, StringComparison.Ordinal))
            return;

        bool wasFiltering = _activeFilter.Length > 0;
        _activeFilter = filter;
        bool filtering = filter.Length > 0;

        int totalVisible = 0;
        for (int g = 0; g < _groups.Count; g++)
        {
            CategoryGroup group = _groups[g];
            if (wasFiltering != filtering)
            {
                // A filter session starts with every matching category expanded; collapses made during it are dropped.
                group.CollapsedWhileFiltering = false;
            }

            int visible = 0;
            for (int i = 0; i < group.Rows.Count; i++)
            {
                PropertyRow row = group.Rows[i];
                bool matches = MatchesFilter(row.Descriptor, filter);
                row.Visibility = matches ? Visibility.Visible : Visibility.Collapsed;
                if (matches) visible++;
            }

            group.VisibleCount = visible;
            totalVisible += visible;
            group.Header.Visibility = visible > 0 ? Visibility.Visible : Visibility.Collapsed;
            if (group.DisplayedCount != visible)
            {
                group.DisplayedCount = visible;
                group.CountText.Text = $"({visible})";
            }
            UpdateGroupExpansion(group);
        }

        string? message = null;
        if (SelectedObject == null)
        {
            message = "No object selected for inspection";
        }
        else if (_rows.Count == 0)
        {
            message = "No inspectable properties found on selected object";
        }
        else if (totalVisible == 0)
        {
            message = $"No properties match \"{filter}\"";
        }

        if (message != null)
        {
            _placeholderText.Text = message;
            _placeholder.Visibility = Visibility.Visible;
        }
        else
        {
            _placeholder.Visibility = Visibility.Collapsed;
        }
    }

    private static bool MatchesFilter(IPropertyDescriptor prop, string filter)
    {
        if (filter.Length == 0)
            return true;

        return Contains(prop.DisplayName, filter) || Contains(prop.Name, filter) || Contains(prop.Category, filter);

        static bool Contains(string? text, string value) =>
            text != null && text.Contains(value, StringComparison.OrdinalIgnoreCase);
    }

    private CategoryGroup CreateGroup(string name)
    {
        var chevron = new Icon
        {
            Kind = MaterialIconKind.ExpandMore,
            Size = 18,
            VerticalAlignment = VerticalAlignment.Center
        };

        var countText = new TextBlock(string.Empty)
        {
            FontSize = 11,
            Foreground = s_mutedText,
            VerticalAlignment = VerticalAlignment.Center
        };

        var headerContent = new StackPanel
        {
            Orientation = Orientation.Horizontal,
            Spacing = 8,
            VerticalAlignment = VerticalAlignment.Center
        };
        headerContent.Add(chevron);
        headerContent.Add(new TextBlock(name) { Bold = true, FontSize = 12, VerticalAlignment = VerticalAlignment.Center });
        headerContent.Add(countText);

        var itemsPanel = new StackPanel { Orientation = Orientation.Vertical, Spacing = 0 };
        var group = new CategoryGroup(name, chevron, countText, itemsPanel);

        var header = new CategoryHeader(group)
        {
            Padding = new Thickness(10, 8),
            Background = s_headerBackground,
            BorderThickness = new Thickness(0, 0, 0, 1),
            BorderBrush = s_headerBorder,
            Child = headerContent
        };
        header.PointerPressed += _headerPointerPressedHandler;
        group.Header = header;
        return group;
    }

    private PropertyRow CreateRow(IPropertyDescriptor descriptor, object target, int index)
    {
        string displayName = descriptor.DisplayName ?? descriptor.Name ?? string.Empty;

        var labelPanel = new StackPanel
        {
            Orientation = Orientation.Horizontal,
            Spacing = 4,
            VerticalAlignment = VerticalAlignment.Center
        };
        labelPanel.Add(new TextBlock(displayName) { FontSize = 12, VerticalAlignment = VerticalAlignment.Center });

        if (descriptor.IsReadOnly)
        {
            labelPanel.Add(new TextBlock("(Read-Only)")
            {
                FontSize = 10,
                Foreground = s_readOnlyText,
                VerticalAlignment = VerticalAlignment.Center
            });
        }

        var context = new PropertyEditorContext(this, target, descriptor);
        UIElement editor;
        try
        {
            editor = EditorRegistry.CreateEditor(context);
        }
        catch (Exception ex)
        {
            // A failing custom factory must not break the whole grid: show the value read-only with the error.
            editor = PropertyEditorRegistry.CreateFallbackEditor(context);
            context.SetError(ex.Message);
        }
        editor.VerticalAlignment = VerticalAlignment.Center;
        editor.GotFocus += _editorGotFocusHandler;

        var labelColumn = new ColumnDefinition(GridLength.Pixels(LabelWidth));
        var rowGrid = new Grid();
        rowGrid.RowDefinitions.Add(new RowDefinition(GridLength.Auto));
        rowGrid.RowDefinitions.Add(new RowDefinition(GridLength.Auto));
        rowGrid.ColumnDefinitions.Add(labelColumn);
        rowGrid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));

        Grid.SetColumn(labelPanel, 0);
        Grid.SetColumn(editor, 1);
        rowGrid.Add(labelPanel);
        rowGrid.Add(editor);

        var row = new PropertyRow(descriptor, context, displayName, index, labelColumn, rowGrid)
        {
            Padding = new Thickness(12, 6),
            BorderThickness = new Thickness(0, 0, 0, 1),
            BorderBrush = s_rowBorder,
            Child = rowGrid
        };
        row.PointerEntered += _rowPointerEnteredHandler;
        row.PointerExited += _rowPointerExitedHandler;
        row.PointerPressed += _rowPointerPressedHandler;
        row.ShowError(context.Error);
        return row;
    }

    #endregion

    #region Hover, description

    private void OnRowPointerEntered(object? sender, PointerEventArgs e)
    {
        if (sender is not PropertyRow row) return;
        row.UpdateBackground(isHovered: true);
        SetActiveRow(row);
    }

    private void OnRowPointerExited(object? sender, PointerEventArgs e)
    {
        if (sender is PropertyRow row)
        {
            row.UpdateBackground(isHovered: false);
        }
    }

    private void OnRowPointerPressed(object? sender, PointerEventArgs e)
    {
        if (sender is PropertyRow row)
        {
            SetActiveRow(row);
        }
    }

    private void OnEditorGotFocus(object? sender, EventArgs e)
    {
        for (VisualNode? node = sender as VisualNode; node != null; node = node.Parent)
        {
            if (node is PropertyRow row)
            {
                SetActiveRow(row);
                return;
            }
        }
    }

    private void SetActiveRow(PropertyRow row)
    {
        if (ReferenceEquals(_activeRow, row)) return;
        _activeRow = row;
        UpdateDescriptionPanel();
    }

    private void UpdateDescriptionPanel()
    {
        bool visible = IsDescriptionVisible && _hasDescriptions;
        _descriptionPanel.Visibility = visible ? Visibility.Visible : Visibility.Collapsed;
        if (!visible) return;

        _descriptionTitle.Text = _activeRow?.DisplayName ?? string.Empty;
        _descriptionText.Text = _activeRow?.Descriptor.Description ?? string.Empty;
    }

    #endregion

    #region Layout Overrides

    /// <inheritdoc/>
    protected override Size MeasureOverride(Size availableSize)
    {
        _rootBorder.Measure(availableSize);
        return _rootBorder.DesiredSize;
    }

    /// <inheritdoc/>
    protected override Size ArrangeOverride(Size finalSize)
    {
        _rootBorder.Arrange(new Rect(Point.Zero, finalSize));
        return finalSize;
    }

    #endregion

    #region Row and category types

    // One property row; also the anchor of its context, editor and error text (all share the row's lifetime).
    private sealed class PropertyRow : Border
    {
        private TextBlock? _errorText;
        private bool _isHovered;

        public PropertyRow(IPropertyDescriptor descriptor, PropertyEditorContext context, string displayName, int index, ColumnDefinition labelColumn, Grid layout)
        {
            Descriptor = descriptor;
            Context = context;
            DisplayName = displayName;
            Index = index;
            LabelColumn = labelColumn;
            Layout = layout;
            context.ErrorChanged += ShowError;
        }

        public IPropertyDescriptor Descriptor { get; }
        public PropertyEditorContext Context { get; }
        public string DisplayName { get; }
        public int Index { get; }
        public ColumnDefinition LabelColumn { get; }
        public Grid Layout { get; }

        public void ShowError(string? message)
        {
            if (message == null)
            {
                if (_errorText != null)
                {
                    _errorText.Visibility = Visibility.Collapsed;
                }
            }
            else
            {
                if (_errorText == null)
                {
                    _errorText = new TextBlock(string.Empty)
                    {
                        FontSize = 11,
                        Foreground = s_errorText,
                        TextWrapping = TextWrapping.Wrap,
                        Margin = new Thickness(0, 4, 0, 0)
                    };
                    Grid.SetRow(_errorText, 1);
                    Grid.SetColumn(_errorText, 1);
                    Layout.Add(_errorText);
                }
                _errorText.Text = message;
                _errorText.Visibility = Visibility.Visible;
            }
            UpdateBackground(_isHovered);
        }

        public void UpdateBackground(bool isHovered)
        {
            _isHovered = isHovered;
            Background = Context.HasError ? s_errorBackground : isHovered ? s_rowHover : Color.Transparent;
            BorderBrush = Context.HasError ? s_errorText : s_rowBorder;
        }
    }

    private sealed class CategoryHeader(CategoryGroup group) : Border
    {
        public CategoryGroup Group { get; } = group;
    }

    private sealed class CategoryGroup(string name, Icon chevron, TextBlock countText, StackPanel itemsPanel)
    {
        public string Name { get; } = name;
        public Icon Chevron { get; } = chevron;
        public TextBlock CountText { get; } = countText;
        public StackPanel ItemsPanel { get; } = itemsPanel;
        public Border Header { get; set; } = null!;
        public List<PropertyRow> Rows { get; } = [];
        public int VisibleCount { get; set; }
        public int DisplayedCount { get; set; } = -1;
        public bool IsExpanded { get; set; } = true;
        public bool CollapsedWhileFiltering { get; set; }
    }

    #endregion
}
