using System;
using System.Collections.Generic;
using System.Windows.Input;
using Atelier.Core.Keybinding;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Xunit;

namespace Atelier.Tests;

public class KeybindingManagerTests
{
    [Fact]
    public void KeybindingManager_HasGeneratedConstants()
    {
        // Verify the static readonly string generated by Roslyn KeybindingGenerator
        Assert.Equal("Global_Debug", KeybindingManager.GlobalDebugKeybinding);
    }

    [Fact]
    public void KeybindingManager_AutoRegistersDiscoveredKeybindings()
    {
        // Ensure keybindings are registered
        KeybindingManager.Initialize();

        Assert.True(KeybindingManager.RegisteredKeybindings.ContainsKey("Global"));
        Assert.True(KeybindingManager.RegisteredKeybindings["Global"].ContainsKey("Debug"));

        var descriptor = KeybindingManager.RegisteredKeybindings["Global"]["Debug"];
        Assert.NotNull(descriptor);
        Assert.Equal("Debug", descriptor.Name);
        Assert.Equal("Global", descriptor.Group);
        Assert.Equal("F12", descriptor.Keybinding);
        Assert.IsType<DebugCommand>(descriptor.Command);
    }

    [Fact]
    public void KeybindingManager_CanExecute_And_ExecuteKeybinding_WorkByKey()
    {
        bool canExecute = KeybindingManager.CanExecuteKeybinding(KeybindingManager.GlobalDebugKeybinding);
        Assert.True(canExecute);

        // Should execute without throwing
        KeybindingManager.ExecuteKeybinding(KeybindingManager.GlobalDebugKeybinding);
    }

    [Fact]
    public void KeybindingManager_CanExecute_And_ExecuteKeybinding_WorkByGroupAndName()
    {
        bool canExecute = KeybindingManager.CanExecuteKeybinding("Global", "Debug");
        Assert.True(canExecute);

        KeybindingManager.ExecuteKeybinding("Global", "Debug");
    }

    [Fact]
    public void KeybindingManager_Clear_And_ReRegisterGeneratedKeybindings_IsIdempotent()
    {
        KeybindingManager.Clear();
        Assert.Empty(KeybindingManager.RegisteredKeybindings);

        // Re-register
        KeybindingManager.Initialize();
        Assert.True(KeybindingManager.RegisteredKeybindings.ContainsKey("Global"));
        Assert.True(KeybindingManager.RegisteredKeybindings["Global"].ContainsKey("Debug"));

        // Calling again should not throw InvalidOperationException
        KeybindingManager.Initialize();
        Assert.True(KeybindingManager.RegisteredKeybindings["Global"].ContainsKey("Debug"));
    }

    [Fact]
    public void KeybindingManager_CustomDescriptor_RegistrationAndExecution()
    {
        bool executed = false;
        var relay = new AtelierRelayCommand(() => executed = true, () => true);
        var descriptor = new KeybindingDescriptor("Save", "File", "Ctrl+S", relay);

        KeybindingManager.RegisterKeybinding(descriptor);

        Assert.True(KeybindingManager.CanExecuteKeybinding("File_Save"));
        KeybindingManager.ExecuteKeybinding("File_Save");
        Assert.True(executed);
    }

    [Fact]
    public void KeybindingManager_UnknownKeybinding_ThrowsKeyNotFoundException()
    {
        Assert.Throws<KeyNotFoundException>(() =>
        {
            KeybindingManager.ExecuteKeybinding("NonExistent_Keybinding");
        });
    }

    [Fact]
    public void KeybindingManager_InvalidKeyFormat_ThrowsArgumentException()
    {
        Assert.Throws<ArgumentException>(() =>
        {
            KeybindingManager.ExecuteKeybinding("InvalidKeyWithoutSeparator");
        });
    }

    [Fact]
    public void ExternalAssembly_GeneratedKeybindings_RegistersAndExecutes()
    {
        // Generated in Atelier.Generated for Atelier.Tests assembly
        Assert.Equal("Testing_TestEcho", Atelier.Generated.GeneratedKeybindings.TestingTestEchoKeybinding);

        TestEchoCommand.WasExecuted = false;
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        Assert.True(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.TestingTestEchoKeybinding));
        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.TestingTestEchoKeybinding);
        Assert.True(TestEchoCommand.WasExecuted);
    }

    [Fact]
    public void PropertyKeybinding_GeneratesConstants()
    {
        Assert.Equal("global_Increment", Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding);
        Assert.Equal("action_Run", Atelier.Generated.GeneratedKeybindings.ActionRunKeybinding);
    }

    [Fact]
    public void PropertyKeybinding_ExecutesWithExplicitTarget()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        var vm = new CounterViewModel();
        Assert.Equal(0, vm.ClickCount);

        Assert.True(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, vm));
        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, vm);
        Assert.Equal(1, vm.ClickCount);

        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, vm);
        Assert.Equal(2, vm.ClickCount);
    }

    [Fact]
    public void PropertyKeybinding_ExecutesByGroupAndName_WithExplicitTarget()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        var vm = new CounterViewModel();
        Assert.Equal(0, vm.ClickCount);

        Assert.True(KeybindingManager.CanExecuteKeybinding("global", "Increment", vm));
        KeybindingManager.ExecuteKeybinding("global", "Increment", vm);
        Assert.Equal(1, vm.ClickCount);
    }

    [Fact]
    public void PropertyKeybinding_ExecutesWithInstanceExtensionMethod()
    {
        KeybindingManager.Clear();

        var vm = new CounterViewModel();
        Assert.Equal(0, vm.ClickCount);

        // Instance extension method generated for CounterViewModel
        vm.RegisterKeybindings();

        Assert.True(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding));
        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding);
        Assert.Equal(1, vm.ClickCount);
    }

    [Fact]
    public void PropertyKeybinding_ThrowsWhenNoTargetProvided()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        Assert.False(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding));

        Assert.Throws<InvalidOperationException>(() =>
        {
            KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding);
        });
    }

    [Fact]
    public void PropertyKeybinding_ThrowsWhenWrongTargetTypeProvided()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        object wrongTarget = new object();
        Assert.False(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, wrongTarget));

        Assert.Throws<InvalidOperationException>(() =>
        {
            KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, wrongTarget);
        });
    }

    [Fact]
    public void PropertyKeybinding_KeybindingPropertyAttribute_WorksIdentically()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        var actionVm = new ActionViewModel();
        Assert.False(actionVm.DidRun);

        Assert.True(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.ActionRunKeybinding, actionVm));
        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.ActionRunKeybinding, actionVm);
        Assert.True(actionVm.DidRun);
    }
}

[Keybinding(name: "TestEcho", group: "Testing", defaultKeybinding: "Ctrl+T")]
public class TestEchoCommand : AtelierCommand
{
    public static bool WasExecuted { get; set; }

    public override void Execute(object? parameter)
    {
        WasExecuted = true;
    }
}

public partial class CounterViewModel : ObservableObject
{
    public int ClickCount { get; set; }

    [RelayCommand]
    [property: Keybinding("Increment", "global", "F11")]
    private void Increment() => ClickCount++;
}

public partial class ActionViewModel : ObservableObject
{
    public bool DidRun { get; set; }

    [RelayCommand]
    [property: KeybindingProperty("Run", "action", "F9")]
    private void Run() => DidRun = true;
}

