using System;
using System.Collections.Generic;
using System.Windows.Input;
using Atelier.Core.Events;
using Atelier.Core.Keybinding;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Xunit;

namespace Atelier.Tests;

[Collection("KeybindingTests")]
public class KeybindingManagerTests
{
    [Fact]
    public void KeybindingManager_HasGeneratedConstants()
    {
        // Verify the static readonly string generated by Roslyn KeybindingGenerator
        Assert.Equal("Global_Debug", KeybindingManager.GlobalDebugKeybinding);
    }

    [Fact]
    public void KeybindingManager_AutoRegistersDiscoveredKeybindings()
    {
        // Ensure keybindings are registered
        KeybindingManager.Initialize();

        Assert.True(KeybindingManager.RegisteredKeybindings.ContainsKey("Global"));
        Assert.True(KeybindingManager.RegisteredKeybindings["Global"].ContainsKey("Debug"));

        var descriptor = KeybindingManager.RegisteredKeybindings["Global"]["Debug"];
        Assert.NotNull(descriptor);
        Assert.Equal("Debug", descriptor.Name);
        Assert.Equal("Global", descriptor.Group);
        Assert.Equal("F12", descriptor.Keybinding);
        Assert.IsType<DebugCommand>(descriptor.Command);
    }

    [Fact]
    public void KeybindingManager_CanExecute_And_ExecuteKeybinding_WorkByKey()
    {
        KeybindingManager.Initialize();
        bool canExecute = KeybindingManager.CanExecuteKeybinding(KeybindingManager.GlobalDebugKeybinding);
        Assert.True(canExecute);

        // Should execute without throwing
        KeybindingManager.ExecuteKeybinding(KeybindingManager.GlobalDebugKeybinding);
    }

    [Fact]
    public void KeybindingManager_CanExecute_And_ExecuteKeybinding_WorkByGroupAndName()
    {
        KeybindingManager.Initialize();
        bool canExecute = KeybindingManager.CanExecuteKeybinding("Global", "Debug");
        Assert.True(canExecute);

        KeybindingManager.ExecuteKeybinding("Global", "Debug");
    }

    [Fact]
    public void KeybindingManager_Clear_And_ReRegisterGeneratedKeybindings_IsIdempotent()
    {
        KeybindingManager.Clear();
        Assert.Empty(KeybindingManager.RegisteredKeybindings);

        // Re-register
        KeybindingManager.Initialize();
        Assert.True(KeybindingManager.RegisteredKeybindings.ContainsKey("Global"));
        Assert.True(KeybindingManager.RegisteredKeybindings["Global"].ContainsKey("Debug"));

        // Calling again should not throw InvalidOperationException
        KeybindingManager.Initialize();
        Assert.True(KeybindingManager.RegisteredKeybindings["Global"].ContainsKey("Debug"));
    }

    [Fact]
    public void KeybindingManager_CustomDescriptor_RegistrationAndExecution()
    {
        bool executed = false;
        var relay = new AtelierRelayCommand(() => executed = true, () => true);
        var descriptor = new KeybindingDescriptor("Save", "File", "Ctrl+S", relay);

        KeybindingManager.RegisterKeybinding(descriptor);

        Assert.True(KeybindingManager.CanExecuteKeybinding("File_Save"));
        KeybindingManager.ExecuteKeybinding("File_Save");
        Assert.True(executed);
    }

    [Fact]
    public void KeybindingManager_UnknownKeybinding_ThrowsKeyNotFoundException()
    {
        Assert.Throws<KeyNotFoundException>(() =>
        {
            KeybindingManager.ExecuteKeybinding("NonExistent_Keybinding");
        });
    }

    [Fact]
    public void KeybindingManager_InvalidKeyFormat_ThrowsArgumentException()
    {
        Assert.Throws<ArgumentException>(() =>
        {
            KeybindingManager.ExecuteKeybinding("InvalidKeyWithoutSeparator");
        });
    }

    [Fact]
    public void ExternalAssembly_GeneratedKeybindings_RegistersAndExecutes()
    {
        // Generated in Atelier.Generated for Atelier.Tests assembly
        Assert.Equal("Testing_TestEcho", Atelier.Generated.GeneratedKeybindings.TestingTestEchoKeybinding);

        TestEchoCommand.WasExecuted = false;
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        Assert.True(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.TestingTestEchoKeybinding));
        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.TestingTestEchoKeybinding);
        Assert.True(TestEchoCommand.WasExecuted);
    }

    [Fact]
    public void PropertyKeybinding_GeneratesConstants()
    {
        Assert.Equal("global_Increment", Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding);
        Assert.Equal("action_Run", Atelier.Generated.GeneratedKeybindings.ActionRunKeybinding);
    }

    [Fact]
    public void PropertyKeybinding_ExecutesWithExplicitTarget()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        var vm = new CounterViewModel();
        Assert.Equal(0, vm.ClickCount);

        Assert.True(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, vm));
        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, vm);
        Assert.Equal(1, vm.ClickCount);

        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, vm);
        Assert.Equal(2, vm.ClickCount);
    }

    [Fact]
    public void PropertyKeybinding_ExecutesByGroupAndName_WithExplicitTarget()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        var vm = new CounterViewModel();
        Assert.Equal(0, vm.ClickCount);

        Assert.True(KeybindingManager.CanExecuteKeybinding("global", "Increment", vm));
        KeybindingManager.ExecuteKeybinding("global", "Increment", vm);
        Assert.Equal(1, vm.ClickCount);
    }

    [Fact]
    public void PropertyKeybinding_ExecutesWithInstanceExtensionMethod()
    {
        KeybindingManager.Clear();

        var vm = new CounterViewModel();
        Assert.Equal(0, vm.ClickCount);

        // Instance extension method generated for CounterViewModel
        vm.RegisterKeybindings();

        Assert.True(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding));
        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding);
        Assert.Equal(1, vm.ClickCount);
    }

    [Fact]
    public void PropertyKeybinding_ThrowsWhenNoTargetProvided()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        Assert.False(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding));

        Assert.Throws<InvalidOperationException>(() =>
        {
            KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding);
        });
    }

    [Fact]
    public void PropertyKeybinding_ThrowsWhenWrongTargetTypeProvided()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        object wrongTarget = new object();
        Assert.False(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, wrongTarget));

        Assert.Throws<InvalidOperationException>(() =>
        {
            KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.GlobalIncrementKeybinding, wrongTarget);
        });
    }

    [Fact]
    public void PropertyKeybinding_KeybindingPropertyAttribute_WorksIdentically()
    {
        KeybindingManager.Clear();
        Atelier.Generated.GeneratedKeybindings.RegisterKeybindings();

        var actionVm = new ActionViewModel();
        Assert.False(actionVm.DidRun);

        Assert.True(KeybindingManager.CanExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.ActionRunKeybinding, actionVm));
        KeybindingManager.ExecuteKeybinding(Atelier.Generated.GeneratedKeybindings.ActionRunKeybinding, actionVm);
        Assert.True(actionVm.DidRun);
    }

    [Fact]
    public void KeybindingManager_FindKeybinding_MatchesRegardlessOfModifierOrder()
    {
        KeybindingManager.Clear();

        var command = new AtelierRelayCommand(() => { });
        var descriptor = new KeybindingDescriptor("ClearLogs", "Global", "Ctrl+Shift+L", command);
        KeybindingManager.RegisterKeybinding(descriptor);

        // Defined as "Ctrl+Shift+L", but queried as "Shift+Ctrl+L"
        var foundByReversedString = KeybindingManager.FindKeybinding("Global", "Shift+Ctrl+L");
        Assert.NotNull(foundByReversedString);
        Assert.Equal("ClearLogs", foundByReversedString.Name);

        // Queried as "Ctrl+Shift+L"
        var foundByOriginalString = KeybindingManager.FindKeybinding("Global", "Ctrl+Shift+L");
        Assert.NotNull(foundByOriginalString);
        Assert.Equal("ClearLogs", foundByOriginalString.Name);

        // Queried as "Shift, Control, L"
        var foundByCommaFormat = KeybindingManager.FindKeybinding("Global", "Shift, Control, L");
        Assert.NotNull(foundByCommaFormat);
        Assert.Equal("ClearLogs", foundByCommaFormat.Name);

        // Queried with Key and Modifiers
        var foundByKeys = KeybindingManager.FindKeybinding("Global", Key.L, ModifierKeys.Shift | ModifierKeys.Control);
        Assert.NotNull(foundByKeys);
        Assert.Equal("ClearLogs", foundByKeys.Name);

        // Defined with reverse order "Shift+Ctrl+K"
        var reverseDescriptor = new KeybindingDescriptor("TestKey", "Global", "Shift+Ctrl+K", command);
        KeybindingManager.RegisterKeybinding(reverseDescriptor);

        // KeybindingDescriptor normalizes to standard order
        Assert.Equal("Ctrl+Shift+K", reverseDescriptor.Keybinding);

        // Queried as "Ctrl+Shift+K"
        var foundReversed = KeybindingManager.FindKeybinding("Global", "Ctrl+Shift+K");
        Assert.NotNull(foundReversed);
        Assert.Equal("TestKey", foundReversed.Name);
    }

    [Fact]
    public void KeybindingManager_TryExecuteGesture_StringOverload_MatchesRegardlessOfModifierOrder()
    {
        KeybindingManager.Clear();

        bool executed = false;
        var command = new AtelierRelayCommand(() => executed = true);
        var descriptor = new KeybindingDescriptor("TestExec", "CustomGroup", "Ctrl+Shift+T", command);
        KeybindingManager.RegisterKeybinding(descriptor);

        // Execute using "Shift+Ctrl+T"
        bool result = KeybindingManager.TryExecuteGesture("CustomGroup", "Shift+Ctrl+T");
        Assert.True(result);
        Assert.True(executed);

        // Execute across all groups
        executed = false;
        bool crossGroupResult = KeybindingManager.TryExecuteGesture("Shift+Ctrl+T");
        Assert.True(crossGroupResult);
        Assert.True(executed);
    }

    [Fact]
    public void KeybindingManager_GesturesMatch_ComparesCorrectly()
    {
        Assert.True(KeybindingManager.GesturesMatch("Ctrl+Shift+L", "Shift+Ctrl+L"));
        Assert.True(KeybindingManager.GesturesMatch("Ctrl+Alt+Shift+P", "Shift+Ctrl+Alt+P"));
        Assert.True(KeybindingManager.GesturesMatch("Ctrl-Shift-L", "Shift+Ctrl+L"));
        Assert.False(KeybindingManager.GesturesMatch("Ctrl+Shift+L", "Ctrl+Shift+P"));
        Assert.False(KeybindingManager.GesturesMatch("Ctrl+L", "Ctrl+Shift+L"));
    }
}

[Keybinding(name: "TestEcho", group: "Testing", defaultKeybinding: "Ctrl+T")]
public class TestEchoCommand : AtelierCommand
{
    public static bool WasExecuted { get; set; }

    public override void Execute(object? parameter)
    {
        WasExecuted = true;
    }
}

public partial class CounterViewModel : ObservableObject
{
    public int ClickCount { get; set; }

    [RelayCommand]
    [property: Keybinding("Increment", "global", "F11")]
    private void Increment() => ClickCount++;
}

public partial class ActionViewModel : ObservableObject
{
    public bool DidRun { get; set; }

    [RelayCommand]
    [property: KeybindingProperty("Run", "action", "F9")]
    private void Run() => DidRun = true;
}

